name: ycapp_analytics
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.12.2
  firebase_analytics: ^7.0.0
  firebase_messaging: ^8.0.0-dev.12
  shared_preferences: ^0.5.12+4

  ycapp_foundation:
    #path: ../ycapp_foundation
    git:
      url: git://github.com/Johann13/ycapp_foundation.git

dev_dependencies:
  flutter_test:
    sdk: flutter

